export const OFFICIAL_PSC_SPEAKING_TOPICS_METADATA = {
  version: "psc-speaking-topics-2024-01-01",
  effectiveFrom: "2024-01-01",
  sourceUrl: "https://www.xjbz.gov.cn/xjbz/c101441/202309/67e808035ee44f4bbf71e51ba00c0a91.shtml",
  sourceTitle: "普通话水平测试用话题50则〖2024年1月1日起使用〗",
} as const;

export const OFFICIAL_PSC_SPEAKING_TOPICS = [
  "家乡（或熟悉的地方）",
  "假日生活",
  "难忘的旅行",
  "朋友",
  "童年生活",
  "体育运动的乐趣",
  "我了解的地域文化（或风俗）",
  "我所在的学校（或公司、团队、其他机构）",
  "我喜爱的动物",
  "我喜爱的艺术形式",
  "我喜爱的植物",
  "我喜欢的季节（或天气）",
  "我喜欢的节日",
  "我喜欢的美食",
  "我喜欢的职业（或专业）",
  "我欣赏的历史人物",
  "尊敬的人",
  "我的理想（或愿望）",
  "向往的地方",
  "学习普通话（或其他语言）的体会",
  "印象深刻的书籍（或报刊）",
  "谈服饰",
  "谈传统美德",
  "对环境保护的认识",
  "科技发展与社会生活",
  "谈个人修养",
  "谈社会公德（或职业道德）",
  "谈谈卫生与健康",
  "过去的一年",
  "劳动的体会",
  "老师",
  "让我感动的事情",
  "让我快乐的事情",
  "网络时代的生活",
  "我的兴趣爱好",
  "我的一天",
  "珍贵的礼物",
  "我了解的十二生肖",
  "如何保持良好的心态",
  "对垃圾分类的认识",
  "对美的看法",
  "对亲情（或友情、爱情）的理解",
  "对团队精神的理解",
  "对幸福的理解",
  "对终身学习的看法",
  "家庭对个人成长的影响",
  "生活中的诚信",
  "谈中国传统文化",
  "自律与我",
  "小家、大家与国家",
] as const;

const officialTopicSet = new Set<string>(OFFICIAL_PSC_SPEAKING_TOPICS);

export function getSupplementarySpeakingTopics(topics: string[]): string[] {
  return [...new Set(topics.map((topic) => topic.trim()).filter(Boolean))]
    .filter((topic) => !officialTopicSet.has(topic));
}
